### ISSUE TITLE
DXF import have gaps

### ISSUE THREAD

**Issue by pietro-caragiulo** [lab64makerspace/intro2PCBdesign#1]
Hi do you know why I have gaps in the drawing when I import the dxf into kiCAD?

See attached picture:

![image](https://user-images.githubusercontent.com/31522010/51689784-32e1b700-1fac-11e9-81b0-4b39302f842f.png)

I googled the error and tried to check the "Enable Merging" option in the dxf export options.

Thanks

Pietro

**Comment by stevenmclark** [comment]
Hi Pietro,

We saw this when the .dxf is generated in OnShape. I don't know why that happens. We "fixed" that by recreating the sketch in Fusion360 (since that is what is "on" my Mac and then saving the .dxf file. If you want me to do that I would be happy to do so. Please tell me the dimensions and the corner radius you want.

Sorry for the hassle.

**Comment by pietro-caragiulo** [comment]
Thank you Steven, the workaround I used to make my board for this activity was to use the dxf you provided and stretch the edges and corner to the desired size.
I will come and see you to check what is the best way to do the outline for next activities.

Thanks

Pietro

**Comment by stevenmclark** [comment]
'K

See you soon.

All the best-
 Steve
