### ISSUE TITLE
PCB mounting in enclosure, mounting holes, USB connector spacing

### ISSUE THREAD

**Issue by rohanvphadke** [lab64makerspace/intro2PCBdesign#5]
**1. PCB mounting in enclosure**
I was wondering what the plan is for mounting this PCB in the enclosure. The sample DXF file that is provided to us (which is what I'm using) is ok length-wise, but width-wise it'll barely fit.
- PCB width = 1.97in
- enclosure width = 1.962in

Are we going to get spacers and drill holes in the enclosure to mount it?
How will we access the USB connector once the protoboard is inside the enclosure?

**2. Mounting holes**
Is there a guideline for mounting hole placement? What should the clearance be from the board edges? I was thinking a clearance on the order of the hole diameter, but that might be too conservative.

**3. USB connector spacing**
What should the clearance be from the USB connector to the board edges? The sample PCB screenshot doesn't show any overhang, so should we just follow that? The datasheet doesn't have any recommendations either.

**Comment by stevenmclark** [comment]
Hi Rohan,

I think that we tried for "a bridge too far" in this first activity, so don't worry about the placement of the mounting holes for now. The fact the you are asking these questions means that you are aware of the constraints so that;s enough for this exercise.

In "real life" we are either given a mechanical board outline spec by our Mech. E. colleagues or we will have to drag out the model like you have and make sure things fit. In a Solidworks workshop last year we tried to show folks how to do this but my impression was that they found it confusing. I will only give a rough outline here:
1) You select an enclosure and download the model.
2) You generate the sketch for the PCB and then extrude it to .062" (1.6 mm) and save that as a part.
3) You create an assembly that has both the enclosure and the PCB.
4) In most CAD packages you can edit the sketch in the assembly view, so you might constrain two edges to be a particular distance from the edge of the enclosure and measure what needs to be lengthened or shortened, then you change dimensions in the part sketch to achieve the fit you want.
5) Save you new PCB.
6) Go make a DXF (how to do this will depend on the CAD tool, in Solidworks you "make a drawing" then save as a .DXF w/o the borders.

To judge the mounting hole details, we do similar stuff by importing the fasteners we are going to use into the assembly and mating the components and checking clearance. Often the model files can be found at places like McMaster-Carr or Berg or PIC or Small Parts, blah, blah, blah and then you can figure out all the mechanical clearances (and make sure the screw won't go through the bottom of the box!).

For the USB, the same process applies. This is all about using solid models to check out the clearances, etc. I can show you how to do this or if other folks are interested we can have a separate session.

THIS IS THE CRUX OF HAVING THINGS WORK!! So I'm so glad you are thinking about this!

Thank you for the question, sorry for the crude answer.

Please let me know if you want to follow up on this.

All the best-
 Steve
